version: 2

jobs:

  build-test:

    docker:
      - image: circleci/php:7.2-node-browsers

    working_directory: ~/laravel

    steps:

      - checkout

      - run: sudo apt-get install -y libsqlite3-dev zlib1g-dev libpng-dev libjpeg62-turbo-dev
      - run: sudo docker-php-ext-install zip pdo_mysql gd exif
      - run: sudo composer self-update

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: ./vendor/bin/phpunit
      - run: composer cs

workflows:
  version: 2
  build-check:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - master

